remove executable flag from default.xml
seL4/camkes-manifest pull request #10
Opened 2021-09-01 22:50 UTC by axel-h

It seems commit https://github.com/seL4/camkes-manifest/commit/5702351f569cdc6f3593781e8a8ee035ea642e36 broke something in file permissions deep in the git internals, as the file `default.xml` is something between executable and non-executable now. This commit fixes it and make the file non-executable again.

I have tried to dig deeper into the git internals, but gave up at some point because it seems not really worth the time. Seems there is no nice tool that allows debugging a git commit and dump the internal data structures. My guess is that the file `ce_mode` is somehow wrong, which might come from using a git version that is from before the change 
https://github.com/git/git/commit/e44794706eeb57f2ee38ed1604821aa38b8ad9d2 where they decided to track on the executable flag and support 755 and 644 as modes only.

2021-09-01 23:12 UTC, kent-mcleod commented
Can you provide more information about how you are encountering this bug? https://github.com/seL4/camkes-manifest/commit/5702351f569cdc6f3593781e8a8ee035ea642e36 doesn't cause anything abnormal for me on the following git version, and your PR commit appears as an empty commit.  I am unable to find any checkout that causes default.xml to have weird file permissions.
```
$ git --version
git version 2.29.2
```

2021-09-02 01:06 UTC, axel-h commented
I'm using GitKraken and this shows me a rather odd message "File Mode Changes from 217 to 217" for https://github.com/seL4/camkes-manifest/commit/5702351f569cdc6f3593781e8a8ee035ea642e36. I'm in contact with their support about this for quite some time now without much progress. 
Besides this I'm running
```
$ git --version
git version 2.25.1
```
Now, if I run this script, that does not involve GitKraken or touch `default.xml` at all
```
#!/bin/bash -uex

mkdir test
cd test
git clone ssh://git@github.com/seL4/camkes-manifest.git .
git remote add axel-h ssh://git@github.com/axel-h/camkes-manifest.git
git checkout -b testing
echo "foo" > foo.txt
git add foo.txt
git commit -m "foo"
git push -u axel-h
```
The commit that can be seen on that remote branch `testing` will show a change in `default.xml` with the same oss message in the GUI "File Mode Changes from 217 to 217".
![pic](https://user-images.githubusercontent.com/12140423/131761841-5777144a-6c32-4772-bd0b-08a40cbb3b97.png)

This leads me to the conclusion that something is going on internally in git that the normal git tools hide, but the Gitkraken expose (and maybe just should not do). An independent tool that could dump a raw git commits or tree might be able to shed more light on this. The pure python implementation from https://github.com/dulwich/dulwich looks promissing ..
... but actually, there is a much simpler way using https://stackoverflow.com/questions/14790681/what-is-the-internal-format-of-a-git-tree-object to get the raw content of the current master:
```
$ git cat-file tree c77211b08f435a0fee79d18127f0d83ce49dfb80
40000 .github�l-J��6nc��L_�Q/40000 LICENSES>/{���s3ʬT�7`3�ܕ100644 README.mdZ&� ��xy�e5�������100645 default.xml�޽th�z)b
                                                                                                                       >�n��
 �B100644 l4v-master.xmlk�׎I���B���U�{��100644 master.xml�Z!�J��°ƔPF-��40000 snapshots/_�� uV�
                                                                                              t��4�Z��100644 working.xml��9�1@��\��a��
```
where `100645 default.xml` is the interesting thing, this permission are not supposed to be written there. Looking the the "empty" commit 
```
$ git cat-file tree 21067586ea3511039584f509f11b12d8cadc8c24
40000 .github�l-J��6nc��L_�Q/40000 LICENSES>/{���s3ʬT�7`3�ܕ100644 README.mdZ&� ��xy�e5�������100644 default.xml�޽th�z)b
                                                                                                                       >�n��
 �B100644 l4v-master.xmlk�׎I���B���U�{��100644 master.xml�Z!�J��°ƔPF-��40000 snapshots/_�� uV�
                                                                                              t��4�Z��100644 working.xml��9�1@��\��a��
```
This has become `100644 default.xml` now, which fits the the git idea that only `644` (non-executable) or `755` (executable) should be used.
I'l change the commit message to briefly explain this.

2021-09-02 01:16 UTC, lsf37 commented
I'm also having trouble reproducing, I'm getting the following:
```
$ git --version
git version 2.29.2

$ git cat-file -p 5702351
tree 5ab324a14b3b52661ed8a7f80de8e22c0178f3d3
parent bb7b2534d0c81f78d65b07c78f83f8fc8957d028
author Oliver Scott <Oliver.Scott@data61.csiro.au> 1616386944 +1100
committer Oliver Scott <Oliver.Scott@data61.csiro.au> 1616386965 +1100

trivial: add opensbi remove riscv-pk

Signed-off-by: Oliver Scott <Oliver.Scott@data61.csiro.au>

# committed tree
$ git cat-file -p 5ab324a14b3b52661ed8a7f80de8e22c0178f3d3
040000 tree d9016c2d4acfd9366e63f5df044c5fe9512f1b93	.github
040000 tree 3e2f7b95ba9d7333caac54ca03376033f28adc95	LICENSES
100644 blob 5a26f520e3f6780479c3653513dfcee2f8c2e8d5	README.md
100644 blob 90c80fddde445c8f1c7cd74db75958dd20bd628a	default.xml
100644 blob 6ba21cd78e498c9ba242e9c0b7551ba5ba7ba2f2	l4v-master.xml
100644 blob eae4085a0e21f24ab4ccc2b0c6945013462da5a2	master.xml
040000 tree 2f5fe0b3e0207f7556008f0c74a88e34e35a9ffb	snapshots
100644 blob 93ed1039b13140c0d35c141bcf8bb5a2619bce14	working.xml

$ git cat-file -p bb7b2534d0c81f78d65b07c78f83f8fc8957d028
tree ddf91d3ecdf22617f68cc166664138bcbc48030f
parent c87ec5eae42c5a6a99e52194e87a928cb18e8cb2
author Bamboo <bamboo@bitbucket.ts.data61.csiro.au> 1613029819 +1100
committer Bamboo <bamboo@bitbucket.ts.data61.csiro.au> 1613029819 +1100

Updating default.xml
Change-Id: Iccc3de5848e8ab97865fac4a830bd2382737e486

# previous tree
$ git cat-file -p ddf91d3ecdf22617f68cc166664138bcbc48030f
040000 tree d9016c2d4acfd9366e63f5df044c5fe9512f1b93	.github
040000 tree 3e2f7b95ba9d7333caac54ca03376033f28adc95	LICENSES
100644 blob 5a26f520e3f6780479c3653513dfcee2f8c2e8d5	README.md
100644 blob 77037a24f5c5c3aa45466f2ca9146670a822f519	default.xml
100644 blob 6ba21cd78e498c9ba242e9c0b7551ba5ba7ba2f2	l4v-master.xml
100644 blob 1eb427b2bde692386176de080fbf169f5fe54fd9	master.xml
040000 tree 2f5fe0b3e0207f7556008f0c74a88e34e35a9ffb	snapshots
100644 blob 93ed1039b13140c0d35c141bcf8bb5a2619bce14	working.xml
```

I.e. the mode doesn't change in that commit for me. 

And for your commit:
```
$ git cat-file -p 21067586ea3511039584f509f11b12d8cadc8c24
tree 22cabb592bbe9c66204033310d9e2e602291d899
parent c77211b08f435a0fee79d18127f0d83ce49dfb80
author Axel Heider <axelheider@gmx.de> 1630528680 +0200
committer Axel Heider <axelheider@gmx.de> 1630536096 +0200

fix file permissions for default.xml

It seems commit 5702351f569cdc6f3593781e8a8ee035ea642e36 broke something
in file permissions deep in the git internals, as the file default.xml
is something between executable and non-executable now. This commit
fixes it and make the file non-executable again.

Signed-off-by: Axel Heider <axelheider@gmx.de>

# committed tree
$ git cat-file -p 22cabb592bbe9c66204033310d9e2e602291d899
040000 tree d9016c2d4acfd9366e63f5df044c5fe9512f1b93	.github
040000 tree 3e2f7b95ba9d7333caac54ca03376033f28adc95	LICENSES
100644 blob 5a26f520e3f6780479c3653513dfcee2f8c2e8d5	README.md
100644 blob 9edebd74689f0e7a29620b3edf6e99960a20c842	default.xml
100644 blob 6ba21cd78e498c9ba242e9c0b7551ba5ba7ba2f2	l4v-master.xml
100644 blob eae4085a0e21f24ab4ccc2b0c6945013462da5a2	master.xml
040000 tree 2f5fe0b3e0207f7556008f0c74a88e34e35a9ffb	snapshots
100644 blob 93ed1039b13140c0d35c141bcf8bb5a2619bce14	working.xml

# parent commit
$ git cat-file -p c77211b08f435a0fee79d18127f0d83ce49dfb80
tree 07e0c7cb59a916f8edad72b46a0f6bbb1b78c710
parent 458a9ef0f91f9d8504d768e379380c68f76fdc63
author Bamboo <bamboo@bitbucket.ts.data61.csiro.au> 1623401825 +1000
committer Bamboo <bamboo@bitbucket.ts.data61.csiro.au> 1623401825 +1000

Updating default.xml
Change-Id: Iff3715a097be2421e08bda32ce43cb61eeca09ce

# parent tree
$ git cat-file -p 07e0c7cb59a916f8edad72b46a0f6bbb1b78c710
040000 tree d9016c2d4acfd9366e63f5df044c5fe9512f1b93	.github
040000 tree 3e2f7b95ba9d7333caac54ca03376033f28adc95	LICENSES
100644 blob 5a26f520e3f6780479c3653513dfcee2f8c2e8d5	README.md
100644 blob 9edebd74689f0e7a29620b3edf6e99960a20c842	default.xml
100644 blob 6ba21cd78e498c9ba242e9c0b7551ba5ba7ba2f2	l4v-master.xml
100644 blob eae4085a0e21f24ab4ccc2b0c6945013462da5a2	master.xml
040000 tree 2f5fe0b3e0207f7556008f0c74a88e34e35a9ffb	snapshots
100644 blob 93ed1039b13140c0d35c141bcf8bb5a2619bce14	working.xml
```

So there is a new tree object in your commit, but its content appears to be the same as before.

2021-09-02 01:19 UTC, kent-mcleod commented
Ok, thanks for the pointer to `git cat-file tree object`.  Looking myself it looks it's the commits from `bamboo@bitbucket.ts.data61.csiro.au` which set 100645 instead of 100644.

2021-09-02 01:19 UTC, lsf37 commented
Overlapped in time. It looks like you're right, my `git` is hiding the `100645` mode for default.xml and makes it `100644`, I can reproduce if I look at the binary (non-pretty-printed) output.

2021-09-02 01:20 UTC, lsf37 approved these changes

2021-09-02 01:21 UTC, lsf37 commented
I'm happy to merge this, but we should check how it gets introduced and whether the new github CI still does that. Should be visible in sel4test-manifest, which I'll have a look at now.

2021-09-02 01:21 UTC, kent-mcleod requested changes
I'm still not convinced that this is the fix.  sel4test-manfiest also has default.xml with different mode (100645)

2021-09-02 01:24 UTC, lsf37 commented
For which commit do you see that in sel4test? I'm getting 100644 for default.xml

2021-09-02 01:30 UTC, axel-h commented
As said above, I think the change in the git code at https://github.com/git/git/commit/e44794706eeb57f2ee38ed1604821aa38b8ad9d2 is the reason for this. Afterwards there seems an agreement to fix this silently. There is no really a way to prevent this from happening when somebody uses a very old git client or a Windows client that does not care (I think Oliver once told be this might be how this commit was created when I ran into this some time back). I doubt there is a good was to fix this. My advice for the GitKrakren support is now, that they should not report this (an follow what the git cli tools do), then nobody will notice this.
The issue also exists in other repos also, https://github.com/seL4/sel4test-manifest/commit/de37d4e8d25a04ab7630caeb9ae344c075ee98dc added it in `sel4test-manifest` and it seem it came from the same origin.

2021-09-02 01:38 UTC, lsf37 commented
Got it, git/git@e447947 doesn't just pretty print it, it actually removes and normalises the rights. With my git version I can't see any other modes in sel4test. I still do see it in camkes-manifest. Maybe I cloned that with an older git version, not sure.

2021-09-02 01:39 UTC, lsf37 commented
So we can remove it, but we won't notice if it gets re-introduced by someone. At least it doesn't seem to be the CI that is doing it.

2021-09-02 01:42 UTC, kent-mcleod commented
> For which commit do you see that in sel4test? I'm getting 100644 for default.xml

eadd192ca3d5ff8528f0886bead4f5cc6dbdaedb
```
100644 LICENSE_BSD2.txt�ͣ��㦥@�CB"��p��C(100644 README.mdوڝ�
}q�X:ώ�F���%�100645 default.xmlj)�����,n6q���|#100644 master.xml��Y�<��<&���N��-�-
```

2021-09-02 01:50 UTC, kent-mcleod commented
> At least it doesn't seem to be the CI that is doing it

I see the opposite.  Every CI commit to default.xml sets the mode to 100645 in all manifest repositories.

2021-09-02 01:57 UTC, kent-mcleod commented
https://github.com/gitpython-developers/GitPython/issues/1253

2021-09-02 02:12 UTC, kent-mcleod commented
> I see the opposite. Every CI commit to default.xml sets the mode to 100645 in all manifest repositories.

Having switched to the new CI committer in sel4test-manifest the problem stopped happening.  The last commit with the issue I think was https://github.com/seL4/sel4test-manifest/commit/fc17571135c87528f78632bee20e66e8b6edcaed.  This repo hasn't had an update from the new CI committer yet, and when that happens the mode bit should resolve itself.

2021-09-02 02:28 UTC, axel-h commented
This mite be a coincidence. What GitKraken shows me is, that the manual commit https://github.com/seL4/sel4test-manifest/commit/de37d4e8d25a04ab7630caeb9ae344c075ee98dc introduced the issue and the manual commit https://github.com/seL4/sel4test-manifest/commit/f52106a48a64953e889006b93ad3b9253457f72a fixed it. It seems a pure coincidence that the commit https://github.com/seL4/sel4test-manifest/commit/fc17571135c87528f78632bee20e66e8b6edcaed before was the last commit from "Bamboo" and the commit https://github.com/seL4/sel4test-manifest/commit/82a87dec22d6f45c663e06ac0f0d4621d437c243 after is the first commit from "seL4 CI" then. 
But there are commits from Bamboo even before https://github.com/seL4/sel4test-manifest/commit/de37d4e8d25a04ab7630caeb9ae344c075ee98dc where GitKrakte does not show me the permission issues.

2021-09-02 02:43 UTC, kent-mcleod commented
>  But there are commits from Bamboo even before [seL4/sel4test-manifest@de37d4e](https://github.com/seL4/sel4test-manifest/commit/de37d4e8d25a04ab7630caeb9ae344c075ee98dc) where GitKrakte does not show me the permission issues.

The parent of that commit has the wrong mode for default.xml when I check it using `git cat-file index`.  The old CI committer would use gitpython in a docker container to update the default.xml.  Additionally, the bamboo plan had commands that were running `chmod -R o+rwx $PWD` over the same sources that the gitpython scripts were then creating the Update default.xml commits in.

2021-09-02 02:43 UTC, axel-h commented
changed the commit message to explain things a bit more.

2021-09-02 03:27 UTC, axel-h commented
> The parent of that commit has the wrong mode for default.xml when I check it using git cat-file index. The old CI committer would use gitpython in a docker container to update the default.xml. Additionally, the bamboo plan had commands that were running chmod -R o+rwx $PWD over the same sources that the gitpython scripts were then creating the Update default.xml commits in.

Indeed, you are right. Every manual commit fixes the issue and every Bamboo commit introduces it again. I got fooled by the one manual commit I was always looking at, because I though that added it. But the GitKraken GUI always shows the same message "File Mode Changes from 217 to 217" regardless of changing forth or back.

I've changed the commit message again, do you thing that describes it or do you have more background to add there?

2021-09-02 03:43 UTC, lsf37 commented
And the GitHub CI sees a more recent version of GitPython, which would explain why it doesn't re-introduce it.

Ok, that was an interesting ride..

2021-09-02 04:19 UTC, axel-h commented
> Ok, that was an interesting ride..

So, as a follow up, should we consider filtering all PRs through a plain text patch file explicitly? There might be more that git hides and that increases the bandwith of this covert channel. Does this mean a malicious client could put stuff into a tree passed as commit/PR and it would get merged? It's an argument for only accepting plain text patches sent to a mailing list and no PRs at all.

2021-09-09 08:53 UTC, lsf37 commented
@axel-h GitHub CI is now running for `camkes-manifest` and should be fixing up the access right. Could you check if that is the case for you?

2021-09-09 10:51 UTC, axel-h commented
fixed by https://github.com/seL4/camkes-manifest/commit/ca56c963e472f46c87d7d9742ad797db505f5b9b

2021-09-09 10:51 UTC, closed without merging

2021-09-09 10:53 UTC, axel-h commented
rebased and removed the other commit.

2021-09-09 22:41 UTC, lsf37 commented
> So, as a follow up, should we consider filtering all PRs through a plain text patch file explicitly? There might be more that git hides and that increases the bandwith of this covert channel. Does this mean a malicious client could put stuff into a tree passed as commit/PR and it would get merged? It's an argument for only accepting plain text patches sent to a mailing list and no PRs at all.

Sorry, never replied to this part. You can in theory add random objects into the git key-value store, but if they are not referenced by a tag or commit, they don't get transferred on push. If they are referenced, you'll see them. So you have to actually exploit a bug in git to do something nefarious. What we've seen here is basically a coincidence of two bugs (one in command-line git for not normalising and one in the python implementation for producing the inconsistent mode) and a fix that silently ignores the resulting inconsistent state in a tree object.

PRs on GitHub aren't fully guarding against bugs in git, but at least if git on GitHub can process a PR and show the diff etc, then it is reasonable to assume that there is some version of normal command-line git that can deal with it as well. In the very worst case, we get a corrupted repo on GitHub, but it is distributed, all content is protected by hashes, and we would at most lose a few recent commits.

So I think while it is annoying to have triggered the bug, it was essentially harmless and I don't see a real risk of actual content damage.